# ansible file creating vm
---
- name: Create User on Linux VM machine
  hosts: your_vm_group
  become: yes  # To escalate privilege to sudo
  
  tasks:
    - name: Check if user exists
      shell: "getent passwd {{ user_name }}"
      register: user_check
      ignore_errors: yes//
      
    - name: Create user if not exists
      user:
        name: "{{ user_name }}"
        state: present
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"  # Replace 'sha512' with appropriate hashing algorithm
      when: user_check.rc != 0  # If return code is not 0, i.e., user does not exist

